// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CLIENTJOIN_SPIRE_NET_PACKET_H_
#define FLATBUFFERS_GENERATED_CLIENTJOIN_SPIRE_NET_PACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

namespace spire {
namespace net {
namespace packet {

struct ClientJoin;
struct ClientJoinBuilder;

struct ClientJoin FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClientJoinBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_PLAYER_ENTITY_ID = 6
  };
  uint32_t client_id() const {
    return GetField<uint32_t>(VT_CLIENT_ID, 0);
  }
  uint32_t player_entity_id() const {
    return GetField<uint32_t>(VT_PLAYER_ENTITY_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CLIENT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_PLAYER_ENTITY_ID, 4) &&
           verifier.EndTable();
  }
};

struct ClientJoinBuilder {
  typedef ClientJoin Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint32_t client_id) {
    fbb_.AddElement<uint32_t>(ClientJoin::VT_CLIENT_ID, client_id, 0);
  }
  void add_player_entity_id(uint32_t player_entity_id) {
    fbb_.AddElement<uint32_t>(ClientJoin::VT_PLAYER_ENTITY_ID, player_entity_id, 0);
  }
  explicit ClientJoinBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClientJoin> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClientJoin>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClientJoin> CreateClientJoin(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t client_id = 0,
    uint32_t player_entity_id = 0) {
  ClientJoinBuilder builder_(_fbb);
  builder_.add_player_entity_id(player_entity_id);
  builder_.add_client_id(client_id);
  return builder_.Finish();
}

struct ClientJoin::Traits {
  using type = ClientJoin;
  static auto constexpr Create = CreateClientJoin;
};

inline const spire::net::packet::ClientJoin *GetClientJoin(const void *buf) {
  return ::flatbuffers::GetRoot<spire::net::packet::ClientJoin>(buf);
}

inline const spire::net::packet::ClientJoin *GetSizePrefixedClientJoin(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<spire::net::packet::ClientJoin>(buf);
}

inline bool VerifyClientJoinBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<spire::net::packet::ClientJoin>(nullptr);
}

inline bool VerifySizePrefixedClientJoinBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<spire::net::packet::ClientJoin>(nullptr);
}

inline void FinishClientJoinBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::ClientJoin> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedClientJoinBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::ClientJoin> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace packet
}  // namespace net
}  // namespace spire

#endif  // FLATBUFFERS_GENERATED_CLIENTJOIN_SPIRE_NET_PACKET_H_
