// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENTITYTRANSFORMUPDATE_SPIRE_NET_PACKET_H_
#define FLATBUFFERS_GENERATED_ENTITYTRANSFORMUPDATE_SPIRE_NET_PACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "types.hpp"

namespace spire {
namespace net {
namespace packet {

struct EntityTransformUpdate;
struct EntityTransformUpdateBuilder;

struct EntityTransformUpdate FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EntityTransformUpdateBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4,
    VT_POSITION = 6
  };
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  const spire::net::packet::Vector2 *position() const {
    return GetStruct<const spire::net::packet::Vector2 *>(VT_POSITION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID, 4) &&
           VerifyField<spire::net::packet::Vector2>(verifier, VT_POSITION, 4) &&
           verifier.EndTable();
  }
};

struct EntityTransformUpdateBuilder {
  typedef EntityTransformUpdate Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(EntityTransformUpdate::VT_ENTITY_ID, entity_id, 0);
  }
  void add_position(const spire::net::packet::Vector2 *position) {
    fbb_.AddStruct(EntityTransformUpdate::VT_POSITION, position);
  }
  explicit EntityTransformUpdateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EntityTransformUpdate> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EntityTransformUpdate>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EntityTransformUpdate> CreateEntityTransformUpdate(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t entity_id = 0,
    const spire::net::packet::Vector2 *position = nullptr) {
  EntityTransformUpdateBuilder builder_(_fbb);
  builder_.add_position(position);
  builder_.add_entity_id(entity_id);
  return builder_.Finish();
}

struct EntityTransformUpdate::Traits {
  using type = EntityTransformUpdate;
  static auto constexpr Create = CreateEntityTransformUpdate;
};

inline const spire::net::packet::EntityTransformUpdate *GetEntityTransformUpdate(const void *buf) {
  return ::flatbuffers::GetRoot<spire::net::packet::EntityTransformUpdate>(buf);
}

inline const spire::net::packet::EntityTransformUpdate *GetSizePrefixedEntityTransformUpdate(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<spire::net::packet::EntityTransformUpdate>(buf);
}

inline bool VerifyEntityTransformUpdateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<spire::net::packet::EntityTransformUpdate>(nullptr);
}

inline bool VerifySizePrefixedEntityTransformUpdateBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<spire::net::packet::EntityTransformUpdate>(nullptr);
}

inline void FinishEntityTransformUpdateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::EntityTransformUpdate> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEntityTransformUpdateBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::EntityTransformUpdate> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace packet
}  // namespace net
}  // namespace spire

#endif  // FLATBUFFERS_GENERATED_ENTITYTRANSFORMUPDATE_SPIRE_NET_PACKET_H_
