// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ENTITYDESPAWN_SPIRE_NET_PACKET_H_
#define FLATBUFFERS_GENERATED_ENTITYDESPAWN_SPIRE_NET_PACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "types.hpp"

namespace spire {
namespace net {
namespace packet {

struct EntityDespawn;
struct EntityDespawnBuilder;

struct EntityDespawn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef EntityDespawnBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ENTITY_ID = 4
  };
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID, 4) &&
           verifier.EndTable();
  }
};

struct EntityDespawnBuilder {
  typedef EntityDespawn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(EntityDespawn::VT_ENTITY_ID, entity_id, 0);
  }
  explicit EntityDespawnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<EntityDespawn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<EntityDespawn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<EntityDespawn> CreateEntityDespawn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t entity_id = 0) {
  EntityDespawnBuilder builder_(_fbb);
  builder_.add_entity_id(entity_id);
  return builder_.Finish();
}

struct EntityDespawn::Traits {
  using type = EntityDespawn;
  static auto constexpr Create = CreateEntityDespawn;
};

inline const spire::net::packet::EntityDespawn *GetEntityDespawn(const void *buf) {
  return ::flatbuffers::GetRoot<spire::net::packet::EntityDespawn>(buf);
}

inline const spire::net::packet::EntityDespawn *GetSizePrefixedEntityDespawn(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<spire::net::packet::EntityDespawn>(buf);
}

inline bool VerifyEntityDespawnBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<spire::net::packet::EntityDespawn>(nullptr);
}

inline bool VerifySizePrefixedEntityDespawnBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<spire::net::packet::EntityDespawn>(nullptr);
}

inline void FinishEntityDespawnBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::EntityDespawn> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedEntityDespawnBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::EntityDespawn> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace packet
}  // namespace net
}  // namespace spire

#endif  // FLATBUFFERS_GENERATED_ENTITYDESPAWN_SPIRE_NET_PACKET_H_
