// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYERSPAWN_SPIRE_NET_PACKET_H_
#define FLATBUFFERS_GENERATED_PLAYERSPAWN_SPIRE_NET_PACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "types.hpp"

namespace spire {
namespace net {
namespace packet {

struct PlayerSpawn;
struct PlayerSpawnBuilder;

struct PlayerSpawn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerSpawnBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_ENTITY_ID = 6,
    VT_POSITION = 8
  };
  uint32_t client_id() const {
    return GetField<uint32_t>(VT_CLIENT_ID, 0);
  }
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  const spire::net::packet::Vector2 *position() const {
    return GetStruct<const spire::net::packet::Vector2 *>(VT_POSITION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CLIENT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID, 4) &&
           VerifyField<spire::net::packet::Vector2>(verifier, VT_POSITION, 4) &&
           verifier.EndTable();
  }
};

struct PlayerSpawnBuilder {
  typedef PlayerSpawn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint32_t client_id) {
    fbb_.AddElement<uint32_t>(PlayerSpawn::VT_CLIENT_ID, client_id, 0);
  }
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(PlayerSpawn::VT_ENTITY_ID, entity_id, 0);
  }
  void add_position(const spire::net::packet::Vector2 *position) {
    fbb_.AddStruct(PlayerSpawn::VT_POSITION, position);
  }
  explicit PlayerSpawnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerSpawn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerSpawn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerSpawn> CreatePlayerSpawn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t client_id = 0,
    uint32_t entity_id = 0,
    const spire::net::packet::Vector2 *position = nullptr) {
  PlayerSpawnBuilder builder_(_fbb);
  builder_.add_position(position);
  builder_.add_entity_id(entity_id);
  builder_.add_client_id(client_id);
  return builder_.Finish();
}

struct PlayerSpawn::Traits {
  using type = PlayerSpawn;
  static auto constexpr Create = CreatePlayerSpawn;
};

inline const spire::net::packet::PlayerSpawn *GetPlayerSpawn(const void *buf) {
  return ::flatbuffers::GetRoot<spire::net::packet::PlayerSpawn>(buf);
}

inline const spire::net::packet::PlayerSpawn *GetSizePrefixedPlayerSpawn(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<spire::net::packet::PlayerSpawn>(buf);
}

inline bool VerifyPlayerSpawnBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<spire::net::packet::PlayerSpawn>(nullptr);
}

inline bool VerifySizePrefixedPlayerSpawnBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<spire::net::packet::PlayerSpawn>(nullptr);
}

inline void FinishPlayerSpawnBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::PlayerSpawn> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlayerSpawnBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::PlayerSpawn> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace packet
}  // namespace net
}  // namespace spire

#endif  // FLATBUFFERS_GENERATED_PLAYERSPAWN_SPIRE_NET_PACKET_H_
