// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYERDESPAWN_SPIRE_NET_PACKET_H_
#define FLATBUFFERS_GENERATED_PLAYERDESPAWN_SPIRE_NET_PACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "types.hpp"

namespace spire {
namespace net {
namespace packet {

struct PlayerDespawn;
struct PlayerDespawnBuilder;

struct PlayerDespawn FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef PlayerDespawnBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_ENTITY_ID = 6
  };
  uint32_t client_id() const {
    return GetField<uint32_t>(VT_CLIENT_ID, 0);
  }
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CLIENT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID, 4) &&
           verifier.EndTable();
  }
};

struct PlayerDespawnBuilder {
  typedef PlayerDespawn Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint32_t client_id) {
    fbb_.AddElement<uint32_t>(PlayerDespawn::VT_CLIENT_ID, client_id, 0);
  }
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(PlayerDespawn::VT_ENTITY_ID, entity_id, 0);
  }
  explicit PlayerDespawnBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<PlayerDespawn> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<PlayerDespawn>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<PlayerDespawn> CreatePlayerDespawn(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t client_id = 0,
    uint32_t entity_id = 0) {
  PlayerDespawnBuilder builder_(_fbb);
  builder_.add_entity_id(entity_id);
  builder_.add_client_id(client_id);
  return builder_.Finish();
}

struct PlayerDespawn::Traits {
  using type = PlayerDespawn;
  static auto constexpr Create = CreatePlayerDespawn;
};

inline const spire::net::packet::PlayerDespawn *GetPlayerDespawn(const void *buf) {
  return ::flatbuffers::GetRoot<spire::net::packet::PlayerDespawn>(buf);
}

inline const spire::net::packet::PlayerDespawn *GetSizePrefixedPlayerDespawn(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<spire::net::packet::PlayerDespawn>(buf);
}

inline bool VerifyPlayerDespawnBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<spire::net::packet::PlayerDespawn>(nullptr);
}

inline bool VerifySizePrefixedPlayerDespawnBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<spire::net::packet::PlayerDespawn>(nullptr);
}

inline void FinishPlayerDespawnBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::PlayerDespawn> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlayerDespawnBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::PlayerDespawn> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace packet
}  // namespace net
}  // namespace spire

#endif  // FLATBUFFERS_GENERATED_PLAYERDESPAWN_SPIRE_NET_PACKET_H_
