// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SPAWNPLAYER_SPIRE_NET_PACKET_H_
#define FLATBUFFERS_GENERATED_SPAWNPLAYER_SPIRE_NET_PACKET_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 24 &&
              FLATBUFFERS_VERSION_MINOR == 3 &&
              FLATBUFFERS_VERSION_REVISION == 25,
             "Non-compatible flatbuffers version included");

#include "types.hpp"

namespace spire {
namespace net {
namespace packet {

struct SpawnPlayer;
struct SpawnPlayerBuilder;

struct SpawnPlayer FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef SpawnPlayerBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CLIENT_ID = 4,
    VT_ENTITY_ID = 6,
    VT_POSITION = 8
  };
  uint32_t client_id() const {
    return GetField<uint32_t>(VT_CLIENT_ID, 0);
  }
  uint32_t entity_id() const {
    return GetField<uint32_t>(VT_ENTITY_ID, 0);
  }
  const spire::net::packet::Vector2 *position() const {
    return GetStruct<const spire::net::packet::Vector2 *>(VT_POSITION);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_CLIENT_ID, 4) &&
           VerifyField<uint32_t>(verifier, VT_ENTITY_ID, 4) &&
           VerifyField<spire::net::packet::Vector2>(verifier, VT_POSITION, 4) &&
           verifier.EndTable();
  }
};

struct SpawnPlayerBuilder {
  typedef SpawnPlayer Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_client_id(uint32_t client_id) {
    fbb_.AddElement<uint32_t>(SpawnPlayer::VT_CLIENT_ID, client_id, 0);
  }
  void add_entity_id(uint32_t entity_id) {
    fbb_.AddElement<uint32_t>(SpawnPlayer::VT_ENTITY_ID, entity_id, 0);
  }
  void add_position(const spire::net::packet::Vector2 *position) {
    fbb_.AddStruct(SpawnPlayer::VT_POSITION, position);
  }
  explicit SpawnPlayerBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<SpawnPlayer> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<SpawnPlayer>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<SpawnPlayer> CreateSpawnPlayer(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t client_id = 0,
    uint32_t entity_id = 0,
    const spire::net::packet::Vector2 *position = nullptr) {
  SpawnPlayerBuilder builder_(_fbb);
  builder_.add_position(position);
  builder_.add_entity_id(entity_id);
  builder_.add_client_id(client_id);
  return builder_.Finish();
}

struct SpawnPlayer::Traits {
  using type = SpawnPlayer;
  static auto constexpr Create = CreateSpawnPlayer;
};

inline const spire::net::packet::SpawnPlayer *GetSpawnPlayer(const void *buf) {
  return ::flatbuffers::GetRoot<spire::net::packet::SpawnPlayer>(buf);
}

inline const spire::net::packet::SpawnPlayer *GetSizePrefixedSpawnPlayer(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<spire::net::packet::SpawnPlayer>(buf);
}

inline bool VerifySpawnPlayerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<spire::net::packet::SpawnPlayer>(nullptr);
}

inline bool VerifySizePrefixedSpawnPlayerBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<spire::net::packet::SpawnPlayer>(nullptr);
}

inline void FinishSpawnPlayerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::SpawnPlayer> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedSpawnPlayerBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<spire::net::packet::SpawnPlayer> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace packet
}  // namespace net
}  // namespace spire

#endif  // FLATBUFFERS_GENERATED_SPAWNPLAYER_SPIRE_NET_PACKET_H_
