CREATE TYPE UserStatus AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED');

CREATE TYPE UserPlatform AS ENUM ('TEST', 'STEAM');

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,    
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status UserStatus NOT NULL
);